site_name: Omspy Documentation
theme:
  name: material
nav:
  - Home: index.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."] # Explicitly set search path to current directory (project root)
          options:
            show_root_heading: true
            show_source: true
